---
name: 'hostwithquantum/setup-mc'
description: 'Setup the minio client (mc) on GitHub Actions'
branding:
  icon: 'file'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: create bin directory
      run: mkdir ${{ github.action_path }}/bin
      shell: bash
    - name: install the client
      run: |
        curl \
          -H 'Cache-Control: no-cache' \
          "https://dl.minio.io/client/mc/release/linux-amd64/mc" \
          -o ${{ github.action_path }}/bin/mc \
      shell: bash
    - name: make executable
      run: chmod +x ${{ github.action_path }}/bin/mc
      shell: bash
    - name: add to path
      run: echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
      shell: bash
    - run: mc --version
      shell: bash
